"""Source -> target column rename maps for each ingest asset.

Each dict maps raw CSV column names (exactly as they appear in the source
file) to the snake_case names we use downstream. The source names include
whatever odd characters the source applied (spaces, slashes, mixed case);
they are quoted verbatim in the generated SQL.

Keeping these maps here means a dataset's contract with its raw source is
one declarative dict, not scattered SQL SELECT statements.
"""

from __future__ import annotations

BUILDING_FOOTPRINTS: dict[str, str] = {
    "the_geom": "the_geom",
    "NAME": "name",
    "BIN": "bin",
    "DOITT_ID": "doitt_id",
    "SHAPE_AREA": "shape_area",
    "BASE_BBL": "base_bbl",
    "OBJECTID": "objectid",
    "Construction Year": "construction_year",
    "Feature Code": "feature_code",
    "Geometry Source": "geometry_source",
    "Ground Elevation": "ground_elevation",
    "Height Roof": "height_roof",
    "LAST_EDITED_DATE": "last_edited_date",
    "LAST_STATUS_TYPE": "last_status_type",
    "Map Pluto BBL": "map_pluto_bbl",
    "Length": "length",
}

BUILDING_FOOTPRINTS_CASTS: dict[str, str] = {
    "shape_area": "DOUBLE",
    "ground_elevation": "DOUBLE",
    "height_roof": "DOUBLE",
    "length": "DOUBLE",
}

LANDMARKS: dict[str, str] = {
    "the_geom": "the_geom",
    "BIN": "bin",
    "BBL": "bbl",
    "Borough": "borough",
    "Block": "block",
    "Lot": "lot",
    "Des_Addres": "designated_address",
    "Circa": "circa",
    "Date_Low": "date_low",
    "Date_High": "date_high",
    "Date_Combo": "date_combo",
    "Alt_Date_1": "alt_date_1",
    "Alt_Date_2": "alt_date_2",
    "Arch_Build": "architect_builder",
    "Own_Devel": "owner_developer",
    "Alt_Arch_1": "alt_architect_1",
    "Alt_Arch_2": "alt_architect_2",
    "Altered": "altered",
    "Style_Prim": "style_primary",
    "Style_Sec": "style_secondary",
    "Style_Oth": "style_other",
    "Mat_Prim": "material_primary",
    "Mat_Sec": "material_secondary",
    "Mat_Third": "material_third",
    "Mat_Four": "material_fourth",
    "Mat_Other": "material_other",
    "Use_Orig": "use_original",
    "Use_Other": "use_other",
    "Build_Type": "building_type",
    "Build_Oth": "building_type_other",
    "Build_Nme": "building_name",
    "Notes": "notes",
    "Hist_Dist": "historic_district",
    "LM_Orig": "landmark_original",
    "LM_New": "landmark_new",
    "shape_leng": "shape_length",
    "shape_area": "shape_area",
}

LANDMARKS_CASTS: dict[str, str] = {
    "shape_length": "DOUBLE",
    "shape_area": "DOUBLE",
}

SBS_CERTIFIED_BUSINESSES: dict[str, str] = {
    "Account_Number": "account_number",
    "Vendor_Formal_Name": "vendor_formal_name",
    "Vendor_DBA": "vendor_dba",
    "First_Name": "first_name",
    "Last_Name": "last_name",
    "telephone": "telephone",
    "Business_Description": "business_description",
    "Certification": "certification",
    "Certification_Renewal_Date": "certification_renewal_date",
    "Ethnicity": "ethnicity",
    "Address_Line_1": "address_line_1",
    "Address_Line_2": "address_line_2",
    "City": "city",
    "State": "state",
    "Postcode": "postcode",
    "Mailing_Address_Line_1": "mailing_address_line_1",
    "Mailing_Address_Line_2": "mailing_address_line_2",
    "Mailing_City": "mailing_city",
    "Mailing_State": "mailing_state",
    "Mailing_Zip": "mailing_zip",
    "Website": "website",
    "Date_Of_Establishment": "date_of_establishment",
    "Aggregate_Bonding_Limit": "aggregate_bonding_limit",
    "Signatory_To_Union_Contracts": "signatory_to_union_contracts",
    "ID6_digit_NAICS_code": "naics_code",
    "NAICS_Sector": "naics_sector",
    "NAICS_Subsector": "naics_subsector",
    "NAICS_Title": "naics_title",
    "Types_of_Construction_Projects_Performed": "construction_project_types",
    "NIGP_codes": "nigp_codes",
    "Name_of_Client_Job_Exp_1": "client_job_exp_1",
    "Largest_Value_of_Contract": "largest_contract_value",
    "Percent_Self_Performed_Job_Exp_1": "pct_self_performed_1",
    "Date_of_Work_Job_Exp_1": "date_of_work_1",
    "Description_of_Work_Job_Exp_1": "description_of_work_1",
    "Name_of_Client_Job_Exp_2": "client_job_exp_2",
    "Value_of_Contract_Job_Exp_2": "contract_value_2",
    "Percent_Self_Performed_Job_Exp_2": "pct_self_performed_2",
    "Date_of_Work_Job_Exp_2": "date_of_work_2",
    "Description_of_Work_Job_Exp_2": "description_of_work_2",
    "Name_of_Client_Job_Exp_3": "client_job_exp_3",
    "Value_of_Contract_Job_Exp_3": "contract_value_3",
    "Percent_Self_Performed_Job_Exp_3": "pct_self_performed_3",
    "Date_of_Work_Job_Exp_3": "date_of_work_3",
    "Description_of_Work_Job_Exp_3": "description_of_work_3",
    "Capacity_Building_Programs": "capacity_building_programs",
    "Enrolled_in_PASSPort": "enrolled_in_passport",
    "Borough": "borough",
    "Latitude": "latitude",
    "Longitude": "longitude",
    "Community Board": "community_board",
    "Council District": "council_district",
    "BIN": "bin",
    "BBL": "bbl",
    "Census Tract (2020)": "census_tract_2020",
    "Neighborhood Tabulation Area (NTA) (2020)": "nta_2020",
}

SBS_CASTS: dict[str, str] = {
    "latitude": "DOUBLE",
    "longitude": "DOUBLE",
}

ISSUED_LICENSES: dict[str, str] = {
    "License Number": "license_number",
    "Business Name": "business_name",
    "DBA/Trade Name": "dba_trade_name",
    "Business Unique ID": "business_unique_id",
    "Business Category": "business_category",
    "License Type": "license_type",
    "License Status": "license_status",
    "Initial Issuance Date": "initial_issuance_date",
    "Expiration Date": "expiration_date",
    "Details": "details",
    "Contact Phone": "contact_phone",
    "Address Type": "address_type",
    "Building Number": "building_number",
    "Street1": "street1",
    "Street2": "street2",
    "Street3": "street3",
    "Unit Type": "unit_type",
    "Apt/Suite": "apt_suite",
    "City": "city",
    "State": "state",
    "ZIP Code": "zip_code",
    "Borough": "borough",
    "Community Board": "community_board",
    "Council District": "council_district",
    "BIN": "bin",
    "BBL": "bbl",
    "NTA": "nta",
    "Census Block (2010)": "census_block_2010",
    "Census Tract (2010)": "census_tract_2010",
    "Latitude": "latitude",
    "Longitude": "longitude",
}

LICENSES_CASTS: dict[str, str] = {
    "latitude": "DOUBLE",
    "longitude": "DOUBLE",
}

RETAIL_FOOD_STORES: dict[str, str] = {
    "Georeference": "georeference",
    "County": "county",
    "License Number": "license_number",
    "Operation Type": "operation_type",
    "Establishment Type": "establishment_type",
    "Entity Name": "entity_name",
    "DBA Name": "dba_name",
    "Street Number": "street_number",
    "Street Name": "street_name",
    "Address Line 2": "address_line_2",
    "Address Line 3": "address_line_3",
    "City": "city",
    "State": "state",
    "Zip Code": "zip_code",
    "Square Footage": "square_footage",
}

RETAIL_FOOD_CASTS: dict[str, str] = {
    "square_footage": "INTEGER",
}

ACTIVE_CORPORATIONS: dict[str, str] = {
    "DOS ID": "dos_id",
    "Current Entity Name": "entity_name",
    "Initial DOS Filing Date": "initial_filing_date",
    "County": "county",
    "Jurisdiction": "jurisdiction",
    "Entity Type": "entity_type",
    "DOS Process Name": "dos_process_name",
    "DOS Process Address 1": "dos_process_address_1",
    "DOS Process Address 2": "dos_process_address_2",
    "DOS Process City": "dos_process_city",
    "DOS Process State": "dos_process_state",
    "DOS Process Zip": "dos_process_zip",
    "CEO Name": "ceo_name",
    "CEO Address 1": "ceo_address_1",
    "CEO Address 2": "ceo_address_2",
    "CEO City": "ceo_city",
    "CEO State": "ceo_state",
    "CEO Zip": "ceo_zip",
    "Registered Agent Name": "registered_agent_name",
    "Registered Agent Address 1": "registered_agent_address_1",
    "Registered Agent Address 2": "registered_agent_address_2",
    "Registered Agent City": "registered_agent_city",
    "Registered Agent State": "registered_agent_state",
    "Registered Agent Zip": "registered_agent_zip",
    "Location Name": "location_name",
    "Location Address 1": "location_address_1",
    "Location Address 2": "location_address_2",
    "Location City": "location_city",
    "Location State": "location_state",
    "Location Zip": "location_zip",
}
